//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class allegati
    {
        public int id { get; set; }
        public string tipo_origine_allegato { get; set; }
        public int id_origine { get; set; }
        public string path_allegato { get; set; }
        public string descrizione { get; set; }
    }
}
