//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class anagrafica_ospiti
    {
        public int id { get; set; }
        public string uid { get; set; }
        public string codice_interno { get; set; }
        public string cognome { get; set; }
        public string nome { get; set; }
        public Nullable<System.DateTime> data_nascita { get; set; }
        public string comune_nascita { get; set; }
        public string provincia_nascita { get; set; }
        public string cap_nascita { get; set; }
        public string codice_fiscale { get; set; }
        public string provenienza { get; set; }
        public string titolo_studio { get; set; }
        public string professione { get; set; }
        public string stato_civile { get; set; }
        public string nome_coniuge { get; set; }
        public string cognome_coniuge { get; set; }
        public string libretto_sanitario { get; set; }
        public string numero_esenzione_ticket { get; set; }
        public string grado_invalidita { get; set; }
        public string indennita_accompagnamento { get; set; }
        public string pensioni_rendite { get; set; }
        public string codice_medico_curante { get; set; }
        public string nucleo { get; set; }
        public Nullable<System.DateTime> data_ingresso { get; set; }
        public Nullable<System.DateTime> data_uscita { get; set; }
        public string motivo_uscita { get; set; }
        public string indirizzo_residenza { get; set; }
        public string localita_residenza { get; set; }
        public string provincia_residenza { get; set; }
        public string cap_residenza { get; set; }
        public string indirizzo_domicilio { get; set; }
        public string localita_domicilio { get; set; }
        public string provincia_domicilio { get; set; }
        public string cap_domicilio { get; set; }
        public string nome_cognome_emergenza { get; set; }
        public string telefono_emergenza { get; set; }
        public string nome_parente1 { get; set; }
        public string cognome_parente1 { get; set; }
        public string rapporto_parente1 { get; set; }
        public string telefono_parente1 { get; set; }
        public string indirizzo_parente1 { get; set; }
        public string localita_parente1 { get; set; }
        public string provincia_parente1 { get; set; }
        public string note_parente1 { get; set; }
        public string nome_parente2 { get; set; }
        public string cognome_parente2 { get; set; }
        public string rapporto_parente2 { get; set; }
        public string telefono_parente2 { get; set; }
        public string indirizzo_parente2 { get; set; }
        public string localita_parente2 { get; set; }
        public string provincia_parente2 { get; set; }
        public string note_parente2 { get; set; }
        public string nome_parente3 { get; set; }
        public string cognome_parente3 { get; set; }
        public string rapporto_parente3 { get; set; }
        public string telefono_parente3 { get; set; }
        public string indirizzo_parente3 { get; set; }
        public string localita_parente3 { get; set; }
        public string provincia_parente3 { get; set; }
        public string note_parente3 { get; set; }
        public string residenza_sanitaria_assistenziale { get; set; }
        public string residenza_assistenziale { get; set; }
        public string residenza_assistenziale_alberghiera { get; set; }
        public string nome_cognome { get; set; }
        public string cpccchk { get; set; }
        public string enabled { get; set; }
    }
}
