//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comuni
    {
        public string nome_comun { get; set; }
        public string provincia { get; set; }
        public Nullable<int> cap { get; set; }
        public string nazione { get; set; }
        public string codcatasto { get; set; }
        public string cpccchk { get; set; }
    }
}
