//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IngestDBEntities : DbContext
    {
        public IngestDBEntities()
            : base("name=IngestDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<comuni> comuni { get; set; }
        public virtual DbSet<diari> diari { get; set; }
        public virtual DbSet<dieta> dieta { get; set; }
        public virtual DbSet<personale_collaboratori> personale_collaboratori { get; set; }
        public virtual DbSet<province> province { get; set; }
        public virtual DbSet<regioni> regioni { get; set; }
        public virtual DbSet<settings> settings { get; set; }
        public virtual DbSet<anagrafica_ospiti> anagrafica_ospiti { get; set; }
        public virtual DbSet<anagrafica_medici> anagrafica_medici { get; set; }
        public virtual DbSet<nuclei> nuclei { get; set; }
    }
}
