//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class movimenti_rilevazioni
    {
        public int id { get; set; }
        public Nullable<int> id_tipo_rilevazione { get; set; }
        public Nullable<int> id_tipo_giro { get; set; }
        public Nullable<System.DateTime> data_rilevazione { get; set; }
        public Nullable<System.TimeSpan> ora_rilevazione { get; set; }
        public Nullable<int> operatore { get; set; }
        public Nullable<decimal> valore_numerico { get; set; }
        public Nullable<decimal> valore_numerico2 { get; set; }
        public string unitamisura { get; set; }
        public Nullable<bool> valore_boolean { get; set; }
        public string valore_testo { get; set; }
        public string nota { get; set; }
    }
}
