//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class personale_collaboratori
    {
        public string id { get; set; }
        public string cognome { get; set; }
        public string nome { get; set; }
        public Nullable<System.DateTime> data_nasci { get; set; }
        public string comune_nascita { get; set; }
        public string provincia_nascita { get; set; }
        public string cap_nascita { get; set; }
        public string codice_fiscale { get; set; }
        public string mansione { get; set; }
        public string tipo_collaborazione { get; set; }
        public string indirizzo_residenza { get; set; }
        public string localita_residenza { get; set; }
        public string provincia_residenza { get; set; }
        public string cap_residenza { get; set; }
        public Nullable<System.DateTime> data_inizio_rapporto { get; set; }
        public Nullable<System.DateTime> data_fine_rapporto { get; set; }
        public Nullable<int> user_id { get; set; }
        public string cpccchk { get; set; }
    }
}
