//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class regioni
    {
        public string nazione { get; set; }
        public string codice { get; set; }
        public string descrizion { get; set; }
        public Nullable<decimal> codf24 { get; set; }
        public string cpccchk { get; set; }
    }
}
