//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class schede_ospiti
    {
        public int id { get; set; }
        public Nullable<decimal> tiposcheda { get; set; }
        public decimal id_ospite { get; set; }
        public string oggetto { get; set; }
        public string descrizione { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<System.DateTime> data_ora { get; set; }
    }
}
