//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class terapie_ospiti
    {
        public int id { get; set; }
        public Nullable<int> ospite { get; set; }
        public Nullable<System.DateTime> data_inizio { get; set; }
        public Nullable<System.DateTime> data_fine { get; set; }
        public string farmaco { get; set; }
        public string posologia { get; set; }
        public string via_somministrazione { get; set; }
        public Nullable<int> stato { get; set; }
        public string colazione { get; set; }
        public string pranzo { get; set; }
        public string cena { get; set; }
        public string sera { get; set; }
        public Nullable<System.TimeSpan> ora_inizio { get; set; }
        public Nullable<System.TimeSpan> ora_fine { get; set; }
        public string fascia_terapia { get; set; }
    }
}
