//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipi_rilevazioni
    {
        public int id { get; set; }
        public string descrizione { get; set; }
        public string descrizione_breve { get; set; }
        public string tipo_valore { get; set; }
        public Nullable<int> numero_decimali { get; set; }
        public Nullable<decimal> range_min1 { get; set; }
        public Nullable<decimal> range_min2 { get; set; }
        public Nullable<decimal> range_max1 { get; set; }
        public Nullable<decimal> range_max2 { get; set; }
        public Nullable<int> id_tipo_giro { get; set; }
        public string unita_misura { get; set; }
        public string stato { get; set; }
    }
}
